version: "3"
services:
    rabbitmq:
        image: rabbitmq:alpine
    mongodb:
        image: mongo
    redis:
        build: 
            context: ./redis
    sensor-service:
        build: 
            context: ./service
        environment:
            - APP_RABBITMQ_HOST=rabbitmq
            - APP_MONGODB_HOST=mongodb
        command: sh -c './wait-for-it.sh rabbitmq:5672; ./wait-for-it.sh mongodb:27017 -- java -jar app.jar'
    api:
        build:
            context: ./api
        environment: 
            - APP_RABBITMQ_HOST=rabbitmq
            - APP_REDIS_HOST=redis
        command: sh -c './wait-for-it.sh rabbitmq:5672; ./wait-for-it.sh redis:6379 -- java -jar app.jar'
        ports: 
            - 8080:8080
        depends_on: 
            - redis
