app:
  rabbitmq:
    broadcastSensorExchange: SENSOR_EXCHANGE_BROADCAST
    directSensorExchange: SENSOR_EXCHANGE
    sensorQueue: SENSOR_QUEUE
    sensorReplyQueue: SENSOR_REPLY_QUEUE
    host: localhost
    consumerTimeout: 2000
  redis:
    host: localhost
    port: 6379
    timeout: 2000